const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// Address of the deployed Election contract
const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

// Connect to our local Hardhat blockchain
const provider = new ethers.JsonRpcProvider(
    "http://127.0.0.1:8545"
);

// Load the ABI generated by Hardhat
const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/Election.sol/Election.json"
);

const artifact = JSON.parse(
    fs.readFileSync(artifactPath, "utf8")
);

const contract = new ethers.Contract(
    contractAddress,
    artifact.abi,
    provider
);

module.exports = contract;