import { ethers } from "ethers";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { fileURLToPath } from "url";

dotenv.config();


// Needed because __dirname doesn't exist in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


// Address of the deployed Election contract
const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";


// Connect to our local Hardhat blockchain
const provider = new ethers.JsonRpcProvider(
    process.env.BLOCKCHAIN_RPC_URL
);


const wallet = new ethers.Wallet(
    process.env.BLOCKCHAIN_PRIVATE_KEY,
    provider
);


// Load the ABI generated by Hardhat
const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/Election.sol/Election.json"
);


const artifact = JSON.parse(
    fs.readFileSync(artifactPath, "utf8")
);


const contract = new ethers.Contract(
    contractAddress,
    artifact.abi,
    provider
);


const contractWithSigner = contract.connect(wallet);


export {
    contract,
    contractWithSigner
};